theme: jekyll-theme-minimal
title: "rehabinapinch"
description: "Physiotherapist & Developer Dashboard"

# Optional: Minimal theme specific features
show_downloads: false
google_analytics: # UA-XXXXXXXXX-X (if you have one)
