title: @rehabinapinch
email: rehabinapinch(at)gmail.com
description: Physio Research & App Dashboard
  A hub for research analysis and apps for running and climbing injuries
remote_theme: pages-themes/minimal@v0.2.0
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rehabinapinch.github.io"



